modules:
  player: false # 启用音乐播放器
  fireworks: false # 启用鼠标点击烟花特效
  unlazyHash: false # 启用unlazy hash预览图支持
  visibilityListener: true # 启用可见度监听器
  tabs: true # 启用选项卡扩展支持，如需开启 summary 功能请一并开启
  quiz: true # 启用文章内问题扩展支持
  fancybox: true # 启用 fancybox 支持（不建议禁用）

homeConfig:
  gradient: false # 使用CSS渐变作为文章封面
  # fixedCover 性能比默认的更好，且开启时将启用LCP优化和预加载
  fixedCover: "" # 主页面cover(为空则使用bing随机图片)

sidebar:
  position: left # left/right分别对应左侧/右侧
  avatar: avatar.jpg

alternate: Luna416Blog # 站点大标题

# 页尾全站统计
footer:
  since: 2010 # 开始时间
  count: true # 开启
# 文章界面统计
post:
  count: true # 开启

#使用第三方网站CDN托管图片等，优先加载资源第一梯队preConnect，第二梯队dnsPrefetch
performance:
  # 使用 preconnect 预加载的地址 (不建议超过三个)
  preConnect:
    - "https://pxve.cc/"
    # - "https://lf9-cdn-tos.bytecdntp.com"
  # 使用 dns-prefetch 预解析的地址
  dnsPrefetch:
    # - "https://cdn.jsdelivr.net"
    # - "https://unpkg.com"
# 开启Pagefind索引
pagefind:
  enable: true
